package sing.earthquake.common.streetinfo;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;

import sing.earthquake.bean.BottomMenuBean;

public class StreetInfo {

    public static List<BottomMenuBean> getStreet() {
        List<BottomMenuBean> list = new ArrayList<>();

        list.add(new BottomMenuBean("0", "不限"));
        list.add(new BottomMenuBean("1", "建国门外街道"));
        list.add(new BottomMenuBean("2", "朝阳门外街道"));
        list.add(new BottomMenuBean("3", "呼家楼街道"));
        list.add(new BottomMenuBean("4", "三里屯街道"));
        list.add(new BottomMenuBean("5", "左家庄街道"));
        list.add(new BottomMenuBean("6", "香河园街道"));
        list.add(new BottomMenuBean("7", "和平街街道"));
        list.add(new BottomMenuBean("8", "安贞街道"));
        list.add(new BottomMenuBean("9", "亚运村街道"));
        list.add(new BottomMenuBean("10", "小关街道"));
        list.add(new BottomMenuBean("11", "酒仙桥街道"));
        list.add(new BottomMenuBean("12", "麦子店街道"));
        list.add(new BottomMenuBean("13", "团结湖街道"));
        list.add(new BottomMenuBean("14", "六里屯街道"));
        list.add(new BottomMenuBean("15", "八里庄街道"));
        list.add(new BottomMenuBean("16", "双井街道"));
        list.add(new BottomMenuBean("17", "劲松街道"));
        list.add(new BottomMenuBean("18", "潘家园街道"));
        list.add(new BottomMenuBean("19", "垡头街道"));
        list.add(new BottomMenuBean("20", "南磨房地区"));
        list.add(new BottomMenuBean("21", "高碑店地区"));
        list.add(new BottomMenuBean("22", "将台地区"));
        list.add(new BottomMenuBean("23", "太阳宫地区"));
        list.add(new BottomMenuBean("24", "大屯街道"));
        list.add(new BottomMenuBean("25", "望京街道"));
        list.add(new BottomMenuBean("26", "小红门地区"));
        list.add(new BottomMenuBean("27", "平房地区"));
        list.add(new BottomMenuBean("28", "东风地区"));
        list.add(new BottomMenuBean("29", "奥运村街道"));
        list.add(new BottomMenuBean("30", "来广营地区"));
        list.add(new BottomMenuBean("31", "常营地区"));
        list.add(new BottomMenuBean("32", "三间房地区"));
        list.add(new BottomMenuBean("33", "管庄地区"));
        list.add(new BottomMenuBean("34", "金盏地区"));
        list.add(new BottomMenuBean("35", "孙河地区"));
        list.add(new BottomMenuBean("36", "崔各庄地区"));
        list.add(new BottomMenuBean("37", "东坝地区"));
        list.add(new BottomMenuBean("38", "黑庄户地区"));
        list.add(new BottomMenuBean("39", "豆各庄地区"));
        list.add(new BottomMenuBean("40", "王四营地区"));
        list.add(new BottomMenuBean("41", "首都机场街道"));
        list.add(new BottomMenuBean("42", "东湖街道"));
        list.add(new BottomMenuBean("43", "十八里店地区"));
        list.add(new BottomMenuBean("44", "其他"));

        return list;
    }

    public static List<BottomMenuBean> getCommunity(String id) {
        List<BottomMenuBean> list = new ArrayList<>();
        switch (Integer.parseInt(id)) {
            case 0:
                list.add(new BottomMenuBean("0", "不限"));
                break;
            case 1:
                list.add(new BottomMenuBean("0", "南郎社区"));
                list.add(new BottomMenuBean("0", "北郎社区"));
                list.add(new BottomMenuBean("0", "永安里社区"));
                list.add(new BottomMenuBean("0", "光华里社区"));
                list.add(new BottomMenuBean("0", "建国里社区"));
                list.add(new BottomMenuBean("0", "秀水社区"));
                list.add(new BottomMenuBean("0", "永安里东社区"));
                list.add(new BottomMenuBean("0", "北郎东社区"));
                break;
            case 2:
                list.add(new BottomMenuBean("0", "芳草地社区"));
                list.add(new BottomMenuBean("0", "天福园社区"));
                list.add(new BottomMenuBean("0", "雅宝里社区"));
                list.add(new BottomMenuBean("0", "体东社区"));
                list.add(new BottomMenuBean("0", "吉庆里社区"));
                list.add(new BottomMenuBean("0", "吉祥里社区"));
                list.add(new BottomMenuBean("0", "三丰里社区"));
                break;
            case 3:
                list.add(new BottomMenuBean("0", "小庄社区"));
                list.add(new BottomMenuBean("0", "呼南社区"));
                list.add(new BottomMenuBean("0", "呼北社区"));
                list.add(new BottomMenuBean("0", "关北街社区"));
                list.add(new BottomMenuBean("0", "关东店社区"));
                list.add(new BottomMenuBean("0", "金台社区"));
                list.add(new BottomMenuBean("0", "新街社区"));
                list.add(new BottomMenuBean("0", "核桃园社区"));
                list.add(new BottomMenuBean("0", "东大桥社区"));
                list.add(new BottomMenuBean("0", "金台里社区"));
                break;
            case 4:
                list.add(new BottomMenuBean("0", "幸福一村社区"));
                list.add(new BottomMenuBean("0", "幸福二村社区"));
                list.add(new BottomMenuBean("0", "北三里社区"));
                list.add(new BottomMenuBean("0", "东三里社区"));
                list.add(new BottomMenuBean("0", "中三里社区"));
                list.add(new BottomMenuBean("0", "白西社区"));
                list.add(new BottomMenuBean("0", "中纺里社区"));
                break;
            case 5:
                list.add(new BottomMenuBean("0", "左南里社区"));
                list.add(new BottomMenuBean("0", "左东里社区"));
                list.add(new BottomMenuBean("0", "左北里社区"));
                list.add(new BottomMenuBean("0", "三源里社区"));
                list.add(new BottomMenuBean("0", "静安里社区"));
                list.add(new BottomMenuBean("0", "新源西里社区"));
                list.add(new BottomMenuBean("0", "新源里社区"));
                list.add(new BottomMenuBean("0", "顺源里社区"));
                list.add(new BottomMenuBean("0", "曙光里社区"));
                break;
            case 6:
                list.add(new BottomMenuBean("0", "柳芳南里社区"));
                list.add(new BottomMenuBean("0", "柳芳北里社区"));
                list.add(new BottomMenuBean("0", "西坝河南里社区"));
                list.add(new BottomMenuBean("0", "西坝河中里社区"));
                list.add(new BottomMenuBean("0", "西坝河西里社区"));
                list.add(new BottomMenuBean("0", "西坝河东里社区"));
                list.add(new BottomMenuBean("0", "光熙门北里南社区"));
                list.add(new BottomMenuBean("0", "光熙门北里北社区"));
                list.add(new BottomMenuBean("0", "光熙家园社区"));
                break;
            case 7:
                list.add(new BottomMenuBean("0", "胜古庄社区"));
                list.add(new BottomMenuBean("0", "胜古北社区"));
                list.add(new BottomMenuBean("0", "樱花园社区"));
                list.add(new BottomMenuBean("0", "和平家园社区"));
                list.add(new BottomMenuBean("0", "和平东街社区"));
                list.add(new BottomMenuBean("0", "十四区社区"));
                list.add(new BottomMenuBean("0", "小黄庄社区"));
                list.add(new BottomMenuBean("0", "砖角楼社区"));
                list.add(new BottomMenuBean("0", "煤炭科技苑社区"));
                break;
            case 8:
                list.add(new BottomMenuBean("0", "安华里社区"));
                list.add(new BottomMenuBean("0", "安华西里社区"));
                list.add(new BottomMenuBean("0", "安贞里社区"));
                list.add(new BottomMenuBean("0", "安贞西里社区"));
                list.add(new BottomMenuBean("0", "黄寺社区"));
                list.add(new BottomMenuBean("0", "裕民路社区"));
                break;
            case 9:
                list.add(new BottomMenuBean("0", "北辰东路社区"));
                list.add(new BottomMenuBean("0", "安慧里社区"));
                list.add(new BottomMenuBean("0", "华严北里社区"));
                list.add(new BottomMenuBean("0", "安慧里南社区"));
                list.add(new BottomMenuBean("0", "华西社区"));
                list.add(new BottomMenuBean("0", "丝竹园社区"));
                list.add(new BottomMenuBean("0", "京民社区"));
                list.add(new BottomMenuBean("0", "安苑里社区"));
                list.add(new BottomMenuBean("0", "安翔里社区"));
                list.add(new BottomMenuBean("0", "祁家豁子社区"));
                break;
            case 10:
                list.add(new BottomMenuBean("0", "高原街社区"));
                list.add(new BottomMenuBean("0", "惠新里社区"));
                list.add(new BottomMenuBean("0", "惠新苑社区"));
                list.add(new BottomMenuBean("0", "小关东街社区"));
                list.add(new BottomMenuBean("0", "小关社区"));
                list.add(new BottomMenuBean("0", "惠新北里社区"));
                break;
            case 11:
                list.add(new BottomMenuBean("0", "大山子社区"));
                list.add(new BottomMenuBean("0", "红霞路社区"));
                list.add(new BottomMenuBean("0", "南路社区"));
                list.add(new BottomMenuBean("0", "驼西里社区"));
                list.add(new BottomMenuBean("0", "东路社区"));
                list.add(new BottomMenuBean("0", "怡思苑社区"));
                list.add(new BottomMenuBean("0", "中北路社区"));
                list.add(new BottomMenuBean("0", "电子球场社区"));
                list.add(new BottomMenuBean("0", "高家园社区"));
                break;
            case 12:
                list.add(new BottomMenuBean("0", "农南社区"));
                list.add(new BottomMenuBean("0", "枣南社区"));
                list.add(new BottomMenuBean("0", "朝阳公园社区"));
                list.add(new BottomMenuBean("0", "枣北社区"));
                list.add(new BottomMenuBean("0", "霞光里社区"));
                break;
            case 13:
                list.add(new BottomMenuBean("0", "一二条社区"));
                list.add(new BottomMenuBean("0", "三四条社区"));
                list.add(new BottomMenuBean("0", "中路北社区"));
                list.add(new BottomMenuBean("0", "中路南社区"));
                list.add(new BottomMenuBean("0", "水碓子社区"));
                list.add(new BottomMenuBean("0", "南北里社区"));
                break;
            case 14:
                list.add(new BottomMenuBean("0", "甜水园社区"));
                list.add(new BottomMenuBean("0", "甜水西园社区"));
                list.add(new BottomMenuBean("0", "八里庄南里社区"));
                list.add(new BottomMenuBean("0", "秀水园社区"));
                list.add(new BottomMenuBean("0", "晨光社区"));
                list.add(new BottomMenuBean("0", "六北社区"));
                list.add(new BottomMenuBean("0", "道家园社区"));
                list.add(new BottomMenuBean("0", "炫特家园社区"));
                list.add(new BottomMenuBean("0", "碧水园社区"));
                list.add(new BottomMenuBean("0", "八里庄北里社区"));
                list.add(new BottomMenuBean("0", "十里堡北里社区"));
                break;
            case 15:
                list.add(new BottomMenuBean("0", "华贸中心社区"));
                list.add(new BottomMenuBean("0", "十里堡南里社区"));
                list.add(new BottomMenuBean("0", "红庙社区"));
                list.add(new BottomMenuBean("0", "十里堡社区"));
                list.add(new BottomMenuBean("0", "甘露园社区"));
                list.add(new BottomMenuBean("0", "远洋天地家园社区"));
                list.add(new BottomMenuBean("0", "城市华庭社区"));
                list.add(new BottomMenuBean("0", "甘露园中里"));
                list.add(new BottomMenuBean("0", "八里庄西里"));
                list.add(new BottomMenuBean("0", "朝阳无限社区"));
                list.add(new BottomMenuBean("0", "青年汇"));
                list.add(new BottomMenuBean("0", "罗马家园"));
                list.add(new BottomMenuBean("0", "东里社区"));
                list.add(new BottomMenuBean("0", "延静里社区"));
                list.add(new BottomMenuBean("0", "红庙北里社区"));
                list.add(new BottomMenuBean("0", "华贸第一太平物业公司"));
                list.add(new BottomMenuBean("0", "金网络物业"));
                list.add(new BottomMenuBean("0", "和家安物业"));
                break;
            case 16:
                list.add(new BottomMenuBean("0", "九龙南社区"));
                list.add(new BottomMenuBean("0", "百子园社区"));
                list.add(new BottomMenuBean("0", "九龙社区"));
                list.add(new BottomMenuBean("0", "双花园社区"));
                list.add(new BottomMenuBean("0", "广外南社区"));
                list.add(new BottomMenuBean("0", "大望社区"));
                list.add(new BottomMenuBean("0", "光环社区"));
                list.add(new BottomMenuBean("0", "广泉社区"));
                list.add(new BottomMenuBean("0", "富力社区"));
                list.add(new BottomMenuBean("0", "广和里社区"));
                list.add(new BottomMenuBean("0", "垂西社区"));
                list.add(new BottomMenuBean("0", "垂东社区"));
                break;
            case 17:
                list.add(new BottomMenuBean("0", "劲松北社区"));
                list.add(new BottomMenuBean("0", "劲松东社区"));
                list.add(new BottomMenuBean("0", "劲松西社区"));
                list.add(new BottomMenuBean("0", "劲松中社区"));
                list.add(new BottomMenuBean("0", "农光里社区"));
                list.add(new BottomMenuBean("0", "农光里中社区"));
                list.add(new BottomMenuBean("0", "农光东里社区"));
                list.add(new BottomMenuBean("0", "磨房北里社区"));
                list.add(new BottomMenuBean("0", "八棵杨社区"));
                list.add(new BottomMenuBean("0", "大郊亭社区"));
                list.add(new BottomMenuBean("0", "和谐社区"));
                list.add(new BottomMenuBean("0", "百环社区"));
                list.add(new BottomMenuBean("0", "西大望路社区"));
                break;
            case 18:
                list.add(new BottomMenuBean("0", "磨南社区"));
                list.add(new BottomMenuBean("0", "松东社区"));
                list.add(new BottomMenuBean("0", "潘东社区"));
                list.add(new BottomMenuBean("0", "武东社区"));
                list.add(new BottomMenuBean("0", "松榆里社区"));
                list.add(new BottomMenuBean("0", "松西社区"));
                list.add(new BottomMenuBean("0", "武农社区"));
                list.add(new BottomMenuBean("0", "潘家园社区"));
                list.add(new BottomMenuBean("0", "潘南社区"));
                list.add(new BottomMenuBean("0", "华西社区"));
                list.add(new BottomMenuBean("0", "华北社区"));
                list.add(new BottomMenuBean("0", "华威里社区"));
                break;
            case 19:
                list.add(new BottomMenuBean("0", "一区社区"));
                list.add(new BottomMenuBean("0", "二区社区"));
                list.add(new BottomMenuBean("0", "三区社区"));
                list.add(new BottomMenuBean("0", "北里社区"));
                list.add(new BottomMenuBean("0", "西里社区"));
                list.add(new BottomMenuBean("0", "东里社区"));
                list.add(new BottomMenuBean("0", "翠城馨园社区"));
                list.add(new BottomMenuBean("0", "翠城雅园社区"));
                list.add(new BottomMenuBean("0", "翠城趣园社区"));
                list.add(new BottomMenuBean("0", "翠城盛园社区"));
                list.add(new BottomMenuBean("0", "翠城熙园社区"));
                list.add(new BottomMenuBean("0", "翠城福园社区"));
                list.add(new BottomMenuBean("0", "双合家园社区"));
                break;
            case 20:
                list.add(new BottomMenuBean("0", "紫南社区"));
                list.add(new BottomMenuBean("0", "欢乐谷社区"));
                list.add(new BottomMenuBean("0", "南新园社区"));
                list.add(new BottomMenuBean("0", "平乐园社区"));
                list.add(new BottomMenuBean("0", "百子湾东社区"));
                list.add(new BottomMenuBean("0", "百子湾西社区"));
                list.add(new BottomMenuBean("0", "百子湾北社区"));
                list.add(new BottomMenuBean("0", "赛洛城社区"));
                list.add(new BottomMenuBean("0", "东郊社区"));
                list.add(new BottomMenuBean("0", "双龙社区"));
                list.add(new BottomMenuBean("0", "山水文园社区"));
                break;
            case 21:
                list.add(new BottomMenuBean("0", "小郊亭社区"));
                list.add(new BottomMenuBean("0", "半壁店社区"));
                list.add(new BottomMenuBean("0", "高碑店东社区"));
                list.add(new BottomMenuBean("0", "丽景馨居社区"));
                list.add(new BottomMenuBean("0", "兴隆家园社区"));
                list.add(new BottomMenuBean("0", "甘一社区"));
                list.add(new BottomMenuBean("0", "花北东社区"));
                list.add(new BottomMenuBean("0", "方家园社区"));
                list.add(new BottomMenuBean("0", "通惠家园社区"));
                list.add(new BottomMenuBean("0", "太平庄南社区"));
                list.add(new BottomMenuBean("0", "水南庄社区"));
                list.add(new BottomMenuBean("0", "康西社区"));
                list.add(new BottomMenuBean("0", "康东社区"));
                list.add(new BottomMenuBean("0", "大黄庄社区"));
                list.add(new BottomMenuBean("0", "花北西社区"));
                list.add(new BottomMenuBean("0", "甘露园南里二社区"));
                list.add(new BottomMenuBean("0", "文化园社区"));
                list.add(new BottomMenuBean("0", "力源里社区"));
                list.add(new BottomMenuBean("0", "太平庄社区"));
                list.add(new BottomMenuBean("0", "西店社区"));
                list.add(new BottomMenuBean("0", "太平庄北社区"));
                list.add(new BottomMenuBean("0", "北花园社区"));
                list.add(new BottomMenuBean("0", "高碑店西社区"));
                list.add(new BottomMenuBean("0", "花园闸社区"));
                list.add(new BottomMenuBean("0", "北花园村"));
                list.add(new BottomMenuBean("0", "高碑店村"));
                list.add(new BottomMenuBean("0", "半壁店村"));
                list.add(new BottomMenuBean("0", "八里庄村"));
                list.add(new BottomMenuBean("0", "高井村"));
                break;
            case 22:
                list.add(new BottomMenuBean("0", "水岸家园社区"));
                list.add(new BottomMenuBean("0", "丽都社区"));
                list.add(new BottomMenuBean("0", "梵谷水郡社区"));
                list.add(new BottomMenuBean("0", "芳园里社区"));
                list.add(new BottomMenuBean("0", "将府家园社区"));
                list.add(new BottomMenuBean("0", "瞰都社区"));
                list.add(new BottomMenuBean("0", "安家楼管委会"));
                list.add(new BottomMenuBean("0", "东八间房村"));
                list.add(new BottomMenuBean("0", "驼房营村"));
                break;
            case 23:
                list.add(new BottomMenuBean("0", "芍药居一社区"));
                list.add(new BottomMenuBean("0", "芍药居二社区"));
                list.add(new BottomMenuBean("0", "芍药居三社区"));
                list.add(new BottomMenuBean("0", "芍药居四社区"));
                list.add(new BottomMenuBean("0", "太阳宫社区"));
                list.add(new BottomMenuBean("0", "夏家园社区"));
                list.add(new BottomMenuBean("0", "尚家楼社区"));
                list.add(new BottomMenuBean("0", "牛王庙社区"));
                list.add(new BottomMenuBean("0", "十字口社区"));
                list.add(new BottomMenuBean("0", "惠中庵社区"));
                break;
            case 24:
                list.add(new BottomMenuBean("0", "慧二社区"));
                list.add(new BottomMenuBean("0", "慧北二社区"));
                list.add(new BottomMenuBean("0", "育慧里社区"));
                list.add(new BottomMenuBean("0", "育慧西里社区"));
                list.add(new BottomMenuBean("0", "大屯里社区"));
                list.add(new BottomMenuBean("0", "安慧东里社区"));
                list.add(new BottomMenuBean("0", "安逸社区"));
                list.add(new BottomMenuBean("0", "秀雅社区"));
                list.add(new BottomMenuBean("0", "新新家园社区"));
                list.add(new BottomMenuBean("0", "慧北一社区"));
                list.add(new BottomMenuBean("0", "慧一社区"));
                list.add(new BottomMenuBean("0", "世纪村社区"));
                list.add(new BottomMenuBean("0", "嘉铭园社区"));
                list.add(new BottomMenuBean("0", "欧陆经典社区"));
                break;
            case 25:
                list.add(new BottomMenuBean("0", "望京西园四区社区"));
                list.add(new BottomMenuBean("0", "望京西园三区社区"));
                list.add(new BottomMenuBean("0", "望花路东里社区"));
                list.add(new BottomMenuBean("0", "望花路西里社区"));
                list.add(new BottomMenuBean("0", "花家地社区"));
                list.add(new BottomMenuBean("0", "花家地北里社区"));
                list.add(new BottomMenuBean("0", "花家地南里社区"));
                list.add(new BottomMenuBean("0", "花家地西里社区"));
                list.add(new BottomMenuBean("0", "花家地西里三区社区"));
                list.add(new BottomMenuBean("0", "南湖东园社区"));
                list.add(new BottomMenuBean("0", "南湖中园社区"));
                list.add(new BottomMenuBean("0", "南湖西园社区"));
                list.add(new BottomMenuBean("0", "南湖西里社区"));
                list.add(new BottomMenuBean("0", "方舟苑社区"));
                list.add(new BottomMenuBean("0", "大西洋新城社区"));
                list.add(new BottomMenuBean("0", "爽秋路社区"));
                list.add(new BottomMenuBean("0", "圣星社区"));
                list.add(new BottomMenuBean("0", "望京园社区"));
                list.add(new BottomMenuBean("0", "南湖西园二区社区"));
                list.add(new BottomMenuBean("0", "望京西路社区"));
                list.add(new BottomMenuBean("0", "望京东园五区社区"));
                list.add(new BottomMenuBean("0", "阜荣街社区"));
                break;
            case 26:
                list.add(new BottomMenuBean("0", "中海城社区"));
                list.add(new BottomMenuBean("0", "鸿博家园第一社区"));
                list.add(new BottomMenuBean("0", "恋日绿岛社区"));
                list.add(new BottomMenuBean("0", "鸿博家园第二社区"));
                list.add(new BottomMenuBean("0", "鸿博家园第三社区"));
                list.add(new BottomMenuBean("0", "肖村"));
                list.add(new BottomMenuBean("0", "小红门村"));
                list.add(new BottomMenuBean("0", "龙爪树村"));
                list.add(new BottomMenuBean("0", "牌坊村"));
                break;
            case 27:
                list.add(new BottomMenuBean("0", "富华家园社区"));
                list.add(new BottomMenuBean("0", "姚家园西社区"));
                list.add(new BottomMenuBean("0", "华纺易城社区"));
                list.add(new BottomMenuBean("0", "定福南社区"));
                list.add(new BottomMenuBean("0", "国美家园社区"));
                list.add(new BottomMenuBean("0", "星河湾社区"));
                list.add(new BottomMenuBean("0", "平房社区"));
                list.add(new BottomMenuBean("0", "天鹅湾社区"));
                list.add(new BottomMenuBean("0", "青年路社区"));
                list.add(new BottomMenuBean("0", "姚家园东社区"));
                list.add(new BottomMenuBean("0", "逸翠园社区"));
                list.add(new BottomMenuBean("0", "雅城里社区"));
                list.add(new BottomMenuBean("0", "平房村"));
                list.add(new BottomMenuBean("0", "姚家园村"));
                list.add(new BottomMenuBean("0", "石各庄村"));
                list.add(new BottomMenuBean("0", "黄渠村"));
                break;
            case 28:
                list.add(new BottomMenuBean("0", "石佛营西里社区"));
                list.add(new BottomMenuBean("0", "石佛营东里社区"));
                list.add(new BottomMenuBean("0", "石佛营南里社区"));
                list.add(new BottomMenuBean("0", "紫萝园社区"));
                list.add(new BottomMenuBean("0", "南十里居社区"));
                list.add(new BottomMenuBean("0", "东润枫景社区"));
                list.add(new BottomMenuBean("0", "观湖国际社区"));
                list.add(new BottomMenuBean("0", "泛海国际南社区"));
                list.add(new BottomMenuBean("0", "公园大道社区"));
                list.add(new BottomMenuBean("0", "辛庄村"));
                list.add(new BottomMenuBean("0", "豆各庄村"));
                list.add(new BottomMenuBean("0", "将台洼村"));
                list.add(new BottomMenuBean("0", "六里屯村"));
                list.add(new BottomMenuBean("0", "将台洼居委会"));
                list.add(new BottomMenuBean("0", "辛庄居委会"));
                list.add(new BottomMenuBean("0", "商业公司"));
                break;
            case 29:
                list.add(new BottomMenuBean("0", "南沙滩社区"));
                list.add(new BottomMenuBean("0", "北沙滩社区"));
                list.add(new BottomMenuBean("0", "总装社区"));
                list.add(new BottomMenuBean("0", "科学园社区"));
                list.add(new BottomMenuBean("0", "风林绿洲社区"));
                list.add(new BottomMenuBean("0", "双泉社区"));
                list.add(new BottomMenuBean("0", "林萃社区"));
                list.add(new BottomMenuBean("0", "万科星园社区"));
                list.add(new BottomMenuBean("0", "龙祥社区"));
                list.add(new BottomMenuBean("0", "绿色家园社区"));
                list.add(new BottomMenuBean("0", "大羊坊社区"));
                list.add(new BottomMenuBean("0", "国奥村社区"));
                break;
            case 30:
                list.add(new BottomMenuBean("0", "绣菊园社区"));
                list.add(new BottomMenuBean("0", "新街坊社区"));
                list.add(new BottomMenuBean("0", "青年城社区"));
                list.add(new BottomMenuBean("0", "北苑三号院社区"));
                list.add(new BottomMenuBean("0", "黄金苑社区"));
                list.add(new BottomMenuBean("0", "清河营中路社区"));
                list.add(new BottomMenuBean("0", "北湖渠村"));
                list.add(new BottomMenuBean("0", "红军营村"));
                list.add(new BottomMenuBean("0", "红军营村"));
                list.add(new BottomMenuBean("0", "立城苑社区"));
                list.add(new BottomMenuBean("0", "紫绶园社区"));
                list.add(new BottomMenuBean("0", "时代庄园社区"));
                list.add(new BottomMenuBean("0", "莲葩园社区"));
                list.add(new BottomMenuBean("0", "广达路社区"));
                list.add(new BottomMenuBean("0", "立清路第一社区"));
                list.add(new BottomMenuBean("0", "北苑二号院社区"));
                list.add(new BottomMenuBean("0", "清苑路第一社区"));
                list.add(new BottomMenuBean("0", "茉藜园社区"));
                list.add(new BottomMenuBean("0", "北卫家园社区"));
                list.add(new BottomMenuBean("0", "北苑一号院社区"));
                list.add(new BottomMenuBean("0", "清苑路第二社区"));
                list.add(new BottomMenuBean("0", "来广营村"));
                list.add(new BottomMenuBean("0", "清友园社区"));
                list.add(new BottomMenuBean("0", "红军营社区"));
                list.add(new BottomMenuBean("0", "华贸城社区"));
                list.add(new BottomMenuBean("0", "清河营村"));
                list.add(new BottomMenuBean("0", "新生村"));
                list.add(new BottomMenuBean("0", "朝来绿色家园社区"));
                list.add(new BottomMenuBean("0", "朝来荣盛商业管理有限公司"));
                list.add(new BottomMenuBean("0", "朝阳来广营农工商实业总公司"));
                list.add(new BottomMenuBean("0", "朝来绿色家园物业管理中心"));
                list.add(new BottomMenuBean("0", "北京朝来绿色家园房地产开发有限公司"));
                break;
            case 31:
                list.add(new BottomMenuBean("0", "民族家园社区"));
                list.add(new BottomMenuBean("0", "连心园社区"));
                list.add(new BottomMenuBean("0", "万象新天社区"));
                list.add(new BottomMenuBean("0", "鑫兆家园社区"));
                list.add(new BottomMenuBean("0", "荟万鸿社区"));
                list.add(new BottomMenuBean("0", "苹果派社区"));
                list.add(new BottomMenuBean("0", "常营保利社区"));
                list.add(new BottomMenuBean("0", "畅心阳光社区"));
                list.add(new BottomMenuBean("0", "常营福地社区"));
                list.add(new BottomMenuBean("0", "丽景园社区"));
                list.add(new BottomMenuBean("0", "住欣家园社区"));
                list.add(new BottomMenuBean("0", "像素筹备组"));
                list.add(new BottomMenuBean("0", "龙湖筹备组"));
                list.add(new BottomMenuBean("0", "康德物业"));
                list.add(new BottomMenuBean("0", "中弘文昌物业"));
                break;
            case 32:
                list.add(new BottomMenuBean("0", "定福庄西村"));
                list.add(new BottomMenuBean("0", "东柳村"));
                list.add(new BottomMenuBean("0", "西柳村"));
                list.add(new BottomMenuBean("0", "三西村"));
                list.add(new BottomMenuBean("0", "定福庄东村"));
                list.add(new BottomMenuBean("0", "褡裢坡村"));
                list.add(new BottomMenuBean("0", "白家楼村"));
                list.add(new BottomMenuBean("0", "三东村"));
                list.add(new BottomMenuBean("0", "金家村"));
                list.add(new BottomMenuBean("0", "新房村"));
                list.add(new BottomMenuBean("0", "北双桥村"));
                list.add(new BottomMenuBean("0", "绿洲家园社区"));
                list.add(new BottomMenuBean("0", "定北里社区"));
                list.add(new BottomMenuBean("0", "双桥铁路社区"));
                list.add(new BottomMenuBean("0", "聚福苑社区"));
                list.add(new BottomMenuBean("0", "美然动力社区"));
                list.add(new BottomMenuBean("0", "福怡苑社区"));
                list.add(new BottomMenuBean("0", "定西北里社区"));
                list.add(new BottomMenuBean("0", "双柳社区"));
                list.add(new BottomMenuBean("0", "双桥路社区"));
                list.add(new BottomMenuBean("0", "定西南里社区"));
                list.add(new BottomMenuBean("0", "三南里社区"));
                list.add(new BottomMenuBean("0", "双惠苑社区"));
                list.add(new BottomMenuBean("0", "艺水芳园社区"));
                list.add(new BottomMenuBean("0", "定南里社区"));
                list.add(new BottomMenuBean("0", "泰福苑社区"));
                break;
            case 33:
                list.add(new BottomMenuBean("0", "八里桥社区"));
                list.add(new BottomMenuBean("0", "管庄东里社区"));
                list.add(new BottomMenuBean("0", "管庄西里"));
                list.add(new BottomMenuBean("0", "惠河东里社区"));
                list.add(new BottomMenuBean("0", "惠河西里社区"));
                list.add(new BottomMenuBean("0", "京通苑社区"));
                list.add(new BottomMenuBean("0", "丽景苑社区"));
                list.add(new BottomMenuBean("0", "瑞祥里社区"));
                list.add(new BottomMenuBean("0", "建东苑社区"));
                list.add(new BottomMenuBean("0", "新天地社区"));
                list.add(new BottomMenuBean("0", "东会村"));
                list.add(new BottomMenuBean("0", "郭家场村"));
                list.add(new BottomMenuBean("0", "果家店村"));
                list.add(new BottomMenuBean("0", "塔营村"));
                list.add(new BottomMenuBean("0", "管庄村"));
                list.add(new BottomMenuBean("0", "八里桥村"));
                list.add(new BottomMenuBean("0", "西会村"));
                list.add(new BottomMenuBean("0", "咸宁侯村"));
                list.add(new BottomMenuBean("0", "小寺村"));
                list.add(new BottomMenuBean("0", "杨闸村"));
                list.add(new BottomMenuBean("0", "重兴寺村"));
                list.add(new BottomMenuBean("0", "司辛庄村"));
                break;
            case 34:
                list.add(new BottomMenuBean("0", "金盏家园一社区"));
                list.add(new BottomMenuBean("0", "金盏家园二社区"));
                list.add(new BottomMenuBean("0", "金泽家园一社区"));
                list.add(new BottomMenuBean("0", "金泽家园二社区"));
                list.add(new BottomMenuBean("0", "金盏东村"));
                list.add(new BottomMenuBean("0", "金盏西村"));
                list.add(new BottomMenuBean("0", "小店村"));
                list.add(new BottomMenuBean("0", "雷庄村"));
                list.add(new BottomMenuBean("0", "东村"));
                list.add(new BottomMenuBean("0", "皮村"));
                list.add(new BottomMenuBean("0", "黎各庄村"));
                list.add(new BottomMenuBean("0", "沙窝村"));
                list.add(new BottomMenuBean("0", "马各庄村"));
                break;
            case 35:
                list.add(new BottomMenuBean("0", "康营家园一社区"));
                list.add(new BottomMenuBean("0", "康营家园二社区"));
                list.add(new BottomMenuBean("0", "康营家园三社区"));
                list.add(new BottomMenuBean("0", "康营家园四社区"));
                list.add(new BottomMenuBean("0", "上辛堡村"));
                list.add(new BottomMenuBean("0", "下辛堡村"));
                list.add(new BottomMenuBean("0", "黄港村"));
                list.add(new BottomMenuBean("0", "沙子营村"));
                list.add(new BottomMenuBean("0", "前苇沟村"));
                break;
            case 36:
                list.add(new BottomMenuBean("0", "费家村"));
                list.add(new BottomMenuBean("0", "马南里社区"));
                list.add(new BottomMenuBean("0", "东辛店村"));
                list.add(new BottomMenuBean("0", "草场地村"));
                list.add(new BottomMenuBean("0", "马泉营村"));
                list.add(new BottomMenuBean("0", "奶东村"));
                list.add(new BottomMenuBean("0", "黑桥村"));
                list.add(new BottomMenuBean("0", "南皋村"));
                list.add(new BottomMenuBean("0", "何各庄村"));
                list.add(new BottomMenuBean("0", "京旺家园社区"));
                list.add(new BottomMenuBean("0", "东郊农场"));
                break;
            case 37:
                list.add(new BottomMenuBean("0", "东泽园社区"));
                list.add(new BottomMenuBean("0", "奥园社区"));
                list.add(new BottomMenuBean("0", "福润四季社区"));
                list.add(new BottomMenuBean("0", "高杨树社区"));
                list.add(new BottomMenuBean("0", "朝阳新城社区"));
                list.add(new BottomMenuBean("0", "景和园社区"));
                list.add(new BottomMenuBean("0", "丽富社区"));
                list.add(new BottomMenuBean("0", "红松园社区"));
                list.add(new BottomMenuBean("0", "康静里社区"));
                list.add(new BottomMenuBean("0", "坝鑫家园社区"));
                list.add(new BottomMenuBean("0", "常青藤社区"));
                list.add(new BottomMenuBean("0", "金驹一社区"));
                list.add(new BottomMenuBean("0", "悦和园社区"));
                list.add(new BottomMenuBean("0", "十六局社区"));
                list.add(new BottomMenuBean("0", "金驹二社区"));
                list.add(new BottomMenuBean("0", "东坝家园社区"));
                list.add(new BottomMenuBean("0", "悦和园社区"));
                break;
            case 38:
                list.add(new BottomMenuBean("0", "大鲁店一村"));
                list.add(new BottomMenuBean("0", "大鲁店二村"));
                list.add(new BottomMenuBean("0", "大鲁店三村"));
                list.add(new BottomMenuBean("0", "小鲁店村"));
                list.add(new BottomMenuBean("0", "郎各庄村"));
                list.add(new BottomMenuBean("0", "郎辛庄村"));
                list.add(new BottomMenuBean("0", "黑庄户村"));
                list.add(new BottomMenuBean("0", "四合庄村"));
                list.add(new BottomMenuBean("0", "万子营东村"));
                list.add(new BottomMenuBean("0", "万子营西村"));
                list.add(new BottomMenuBean("0", "双树南村"));
                list.add(new BottomMenuBean("0", "双树北村"));
                list.add(new BottomMenuBean("0", "定辛庄东村"));
                list.add(new BottomMenuBean("0", "定辛庄西村"));
                list.add(new BottomMenuBean("0", "苏坟村"));
                list.add(new BottomMenuBean("0", "幺铺村"));
                list.add(new BottomMenuBean("0", "双桥一社区"));
                list.add(new BottomMenuBean("0", "双桥二社区"));
                list.add(new BottomMenuBean("0", "旭园社区"));
                list.add(new BottomMenuBean("0", "康城社区"));
                list.add(new BottomMenuBean("0", "怡景城社区"));
                break;
            case 39:
                list.add(new BottomMenuBean("0", "清荷里社区筹备组"));
                list.add(new BottomMenuBean("0", "石槽村"));
                list.add(new BottomMenuBean("0", "东马各庄村"));
                list.add(new BottomMenuBean("0", "西马各庄村"));
                list.add(new BottomMenuBean("0", "豆各庄村"));
                list.add(new BottomMenuBean("0", "孟家屯村"));
                list.add(new BottomMenuBean("0", "黄厂村"));
                list.add(new BottomMenuBean("0", "马家湾村"));
                list.add(new BottomMenuBean("0", "水牛坊村"));
                list.add(new BottomMenuBean("0", "孙家坡村"));
                list.add(new BottomMenuBean("0", "文化传播社区"));
                list.add(new BottomMenuBean("0", "青青家园社区"));
                list.add(new BottomMenuBean("0", "京城雅居社区"));
                list.add(new BottomMenuBean("0", "绿丰家园社区"));
                list.add(new BottomMenuBean("0", "阳光家园社区"));
                list.add(new BottomMenuBean("0", "朝丰家园社区"));
                list.add(new BottomMenuBean("0", "富力又一城一社区"));
                list.add(new BottomMenuBean("0", "富力又一城二社区"));
                list.add(new BottomMenuBean("0", "明德园社区筹备组"));
                list.add(new BottomMenuBean("0", "农工商公司"));
                list.add(new BottomMenuBean("0", "金田公园"));
                list.add(new BottomMenuBean("0", "双益达公司"));
                break;
            case 40:
                list.add(new BottomMenuBean("0", "官庄村"));
                list.add(new BottomMenuBean("0", "观音堂村"));
                list.add(new BottomMenuBean("0", "王四营村"));
                list.add(new BottomMenuBean("0", "南花园村"));
                list.add(new BottomMenuBean("0", "道口村"));
                list.add(new BottomMenuBean("0", "孛罗营村"));
                break;
            case 41:
                list.add(new BottomMenuBean("0", "南路西里社区"));
                list.add(new BottomMenuBean("0", "西平街社区"));
                list.add(new BottomMenuBean("0", "南路东里社区"));
                list.add(new BottomMenuBean("0", "南平里社区"));
                break;
            case 42:
                list.add(new BottomMenuBean("0", "望京西园社区"));
                list.add(new BottomMenuBean("0", "果岭里社区"));
                list.add(new BottomMenuBean("0", "南湖东园社区"));
                list.add(new BottomMenuBean("0", "望京花园社区"));
                list.add(new BottomMenuBean("0", "利一社区"));
                list.add(new BottomMenuBean("0", "南湖中园北社区"));
                list.add(new BottomMenuBean("0", "望湖社区"));
                break;
            case 43:
                list.add(new BottomMenuBean("0", "十八里店村"));
                list.add(new BottomMenuBean("0", "吕家营村"));
                list.add(new BottomMenuBean("0", "十里河村"));
                list.add(new BottomMenuBean("0", "周家庄村"));
                list.add(new BottomMenuBean("0", "小武基村"));
                list.add(new BottomMenuBean("0", "老君堂村"));
                list.add(new BottomMenuBean("0", "横街子村"));
                list.add(new BottomMenuBean("0", "西直河村"));
                list.add(new BottomMenuBean("0", "弘善寺居委会"));
                list.add(new BottomMenuBean("0", "白墙子居委会"));
                list.add(new BottomMenuBean("0", "大道口居委会"));
                list.add(new BottomMenuBean("0", "前祁庄居委会"));
                list.add(new BottomMenuBean("0", "后祁庄居委会"));
                list.add(new BottomMenuBean("0", "弘善家园第一社区"));
                list.add(new BottomMenuBean("0", "弘善家园第二社区"));
                list.add(new BottomMenuBean("0", "弘善家园第三社区"));
                list.add(new BottomMenuBean("0", "老君堂社区"));
                break;
            case 44:
                list.add(new BottomMenuBean("0", "其他"));
                break;
            default:
                list = Collections.emptyList();
                break;
        }
        return list;
    }


    public static List<BottomMenuBean> getUsed() {
        List<BottomMenuBean> list = new ArrayList<>();
        list.add(new BottomMenuBean("", "不限"));
        list.add(new BottomMenuBean("", "住宅"));
        list.add(new BottomMenuBean("", "办公楼"));
        list.add(new BottomMenuBean("", "工业厂房"));
        list.add(new BottomMenuBean("", "仓库"));
        list.add(new BottomMenuBean("", "政府"));
        list.add(new BottomMenuBean("", "车库"));
        list.add(new BottomMenuBean("", "幼儿园"));
        list.add(new BottomMenuBean("", "小学"));
        list.add(new BottomMenuBean("", "中学"));
        list.add(new BottomMenuBean("", "大学"));
        list.add(new BottomMenuBean("", "商业"));
        list.add(new BottomMenuBean("", "医院"));
        list.add(new BottomMenuBean("", "人防"));
        list.add(new BottomMenuBean("", "大学"));
        list.add(new BottomMenuBean("", "应急服务"));
        list.add(new BottomMenuBean("", "图书馆"));
        list.add(new BottomMenuBean("", "纪念馆"));
        list.add(new BottomMenuBean("", "博物馆"));
        list.add(new BottomMenuBean("", "体育馆"));
        list.add(new BottomMenuBean("", "电影院"));

        return list;
    }
}